### ISSUE TITLE
关于数据读取问题

### ISSUE THREAD

**Issue by luis-jason** [GW-Wang-thu/StrainNet3D#1]
您好，我注意到在utils的LoadData中，需要使用到idlist.csv文件，但我并没有找到任何关于该文件的信息。可能麻烦你提供一下这个文件包含的内容吗？

**Comment by GW-Wang-thu** [comment]
这个文件里存储的是训练集/测试集中，所有样本的编号代码。如果你到谷歌网盘中看过给出的示例数据集，会发现训练样本/测试样本的命名规则是 id_imgs.npy / id_flow.npy，例如，“1_ imgs.npy”和“1_ flow.npy”构成了一对图像/位移标签训练数据。idlist.csv存储了一个列向量，其中每一行放置一个训练样本的id，例如:
1
2
3
，并且包括了训练集/测试集中所有训练样本的id，放置在训练集文件夹内，告诉程序有哪些训练样本。
如果需要，请回复我的QQ邮箱，我把训练集中的示例样本发给你。单个样本内涉及到四张图像，并组成四组图像对，需要先搞清楚训练集的内容，再使用或修改LoadData.py中读取训练集的代码。

**Comment by luis-jason** [comment]
十分感谢您的回复，我运行了 Generator-of-Stereo-Speckle-images-with-displacement-labels 生成了一些数据。
发现图片的命名规则是 id_L0.tif, id_L1.tif, id_L2.tif, id_L3.tif ...
flow标签的命名规则是 id_FlowX_01.npy, id_FlowY_01.npy ...
如果我想要训练模型，那我应该分别读取图片和标签，然后另外生成一个4通道的npy数组保存图片，一个8通道的npy数组保存标签，以及生成一个对应的idlist.csv文件对吧。

**Comment by GW-Wang-thu** [comment]
是的，单个id对应0，1，2，3四个场景，组成0-1；1-2；1-3；2-3四个变形对；需要一个脚本把图片按照L0-L1-L2-L3-R0-R1-R2-R3，排列成三维uint8格式的npy数组（形状是[8，height, width]，或者，由于只有左相机光流，不添加R0-R3也可以）；再把Flow01-X/Flow01-Y/Flow12-X/Flow12-Y/Flow13-X/Flow13-Y/Flow23-X/Flow23-Y，按照顺序堆叠好，排列成三维uint8格式的npy数组（形状是[8，height, width]），分别命名成id_imgs和id_disps。
这个过程在Generator-of-Stereo-Speckle-images-with-displacement-labels中有实现的脚本，你可以参考[这个文件](https://github.com/GW-Wang-thu/Generator-of-Stereo-Speckle-images-with-displacement-labels/blob/main/utils/GenerateDataset.py)
